---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build
  image: golang:1.13-alpine
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
    GOPROXY: https://mirrors.aliyun.com/goproxy/
    REPO: github.com/micro-in-cn/starter-kit
  commands:
    - tree -L 2
    - go version
    - cd gateway
    - make build
    - ./bin/micro --version