name: default

kind: pipeline
type: docker

steps:
- name: build
  image: golang:1.13-alpine
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
    GOPROXY: https://mirrors.aliyun.com/goproxy/
  commands:
  - go version
  - pwd
  - cd gateway
  - make build
  - ./bin/micro --version