apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: ingress-{{ include "gateway.fullname" . }}-api
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.micro.host.api }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "gateway.fullname" . }}-api
          servicePort: {{ .Values.service.port }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: ingress-{{ include "gateway.fullname" . }}-web
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.micro.host.web }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "gateway.fullname" . }}-web
          servicePort: {{ .Values.service.port }}
