apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "gateway.fullname" . }}-api
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels.api" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway.selectorLabels.api" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: "25m"
        command: [
          {{- include "gateway.command.api" . | nindent 10 }}
        ]
        ports:
        - containerPort: {{ .Values.service.port }}
          name: api-port
