apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway.fullname" . }}-registry
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gateway.fullname" . }}-registry
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gateway.fullname" . }}-registry
subjects:
- kind: ServiceAccount
  name: {{ include "gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
